# Generated by Django 3.2.9 on 2021-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_proposals_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateField()),
                ('jd', models.FloatField(unique=True)),
                ('proposal_no', models.CharField(max_length=20)),
                ('filter_used', models.CharField(max_length=20)),
                ('exposure', models.FloatField()),
                ('air_mass', models.FloatField()),
                ('ccd_temp', models.FloatField()),
                ('image_type', models.CharField(max_length=20)),
                ('focus_value', models.CharField(max_length=20)),
                ('fwhm', models.FloatField()),
                ('lim_mag', models.FloatField()),
                ('psf_mag', models.FloatField()),
                ('psf_merr', models.FloatField()),
                ('apr_mag', models.FloatField()),
                ('apr_merr', models.FloatField()),
                ('filepath', models.CharField(max_length=120, unique=True)),
                ('tel_alt', models.FloatField()),
                ('tel_az', models.FloatField()),
                ('ref_ra', models.FloatField()),
                ('ref_dec', models.FloatField()),
                ('tar_ra', models.FloatField()),
                ('tar_dec', models.FloatField()),
                ('tar_name', models.CharField(max_length=20)),
                ('boundry_points', models.CharField(max_length=120)),
            ],
        ),
    ]
