# Generated by Django 3.2.9 on 2021-12-26 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='apr_mag',
            new_name='avg',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='apr_merr',
            new_name='hour_angle',
        ),
        migrations.AddField(
            model_name='image',
            name='dec_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='lim_mag3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pi',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='progid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='psf_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='psf_zerr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='psf_zp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='ra_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='stdev',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='tile_id',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='boundry_points',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
