# Generated by Django 3.2.9 on 2021-12-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211226_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_observed',
            field=models.DateTimeField(),
        ),
    ]
