# Generated by Django 3.2.9 on 2021-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_image_date_observed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='fwhm',
            field=models.FloatField(null=True),
        ),
    ]
