# Generated by Django 3.2.9 on 2021-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211228_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='air_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='boundry_points',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ccd_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='dec_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='exposure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filter_used',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='focus_value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='hour_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lim_mag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lim_mag3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='progid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='proposal_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_mag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_merr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_zerr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_zp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ra_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ref_dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ref_ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='stdev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tar_dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tar_ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tel_alt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tel_az',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tile_id',
            field=models.FloatField(null=True),
        ),
    ]
