# Generated by Django 3.2.9 on 2022-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211228_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='lim_mag',
            new_name='limmag',
        ),
        migrations.AlterField(
            model_name='image',
            name='jd',
            field=models.FloatField(),
        ),
    ]
