# Generated by Django 3.2.9 on 2022-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220120_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='boundry_points',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='limmag',
        ),
        migrations.AddField(
            model_name='image',
            name='diff_exists',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='healpy_pxl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='lim_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='air_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ccd_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='dec_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='exposure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filter_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='focus_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='fwhm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='hour_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lim_mag3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='progid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='proposal_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_merr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_zerr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='psf_zp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ra_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ref_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ref_ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='stdev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tar_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tar_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='tar_ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tel_alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tel_az',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tile_id',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
