# Generated by Django 3.2.9 on 2022-01-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220123_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ref_dec',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ref_ra',
        ),
        migrations.AddField(
            model_name='image',
            name='header_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='diff_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='healpy_pxl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
