# Generated by Django 3.2.9 on 2022-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220125_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='exposure',
            new_name='exptime',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='focus_value',
            new_name='focuser',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='hour_angle',
            new_name='ha',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='lim_mag',
            new_name='lim_mag5',
        ),
        migrations.RemoveField(
            model_name='image',
            name='psf_zp',
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='center_Dec',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='center_RA',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='obs_cycle',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
