# Generated by Django 3.2.9 on 2022-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='psf_zp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
