# Generated by Django 3.2.9 on 2022-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_image_psf_zp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
