# Generated by Django 3.2.9 on 2021-12-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
